# Generated by Django 3.2.3 on 2021-06-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_votes_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='votes_total',
            new_name='price',
        ),
    ]
