# Generated by Django 3.2.3 on 2021-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210606_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
