# Generated by Django 3.2.3 on 2021-06-06 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_product_title_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title_heading',
        ),
    ]
