# Generated by Django 3.2.3 on 2021-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_product_title_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Solid Neon Colour Adapter', 'Solid Neon Colour Adapter'), ('Solid Neon Color Blunt Box', 'Solid Neon Color Blunt Box'), ('Day Glow Colour Adapter', 'Day Glow Colour Adapter'), ('Day Glow Colour Blunt Box', 'Day Glow Colour Blunt Box'), ('Glow-In-The-Dark Adapter', 'Glow-In-The-Dark Adapter')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('D', 'New'), ('P', 'Best Seller')], max_length=1, null=True),
        ),
    ]
