# Generated by Django 3.2.3 on 2021-06-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog',
        ),
    ]
