# Generated by Django 3.2.3 on 2021-06-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210613_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Solid Neon Colour Adapter', 'Solid Neon Colour Adapter'), ('Solid Neon Color Blunt Box', 'Solid Neon Color Blunt Box'), ('Day Glow Colour Adapter', 'Day Glow Colour Adapter'), ('Day Glow Blunt Colour Box', 'Day Glow Blunt Colour Box'), ('Glow-In-The-Dark Adapter', 'Glow-In-The-Dark Adapter')], max_length=40, null=True),
        ),
    ]
