# Generated by Django 3.2.3 on 2021-06-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='p1'),
            preserve_default=False,
        ),
    ]
