# Generated by Django 3.2.3 on 2021-06-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('CD', 'Creative Designer'), ('F', 'Finance'), ('E', 'Engineering')], max_length=3)),
                ('city', models.CharField(max_length=200)),
                ('prerequisites', models.CharField(choices=[('B', 'Requirement B'), ('A', 'Requirement A')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.TextField()),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.job')),
            ],
        ),
    ]
