# Generated by Django 3.2.3 on 2021-06-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_job_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='prerequisites',
            field=models.CharField(choices=[('A', 'Requirement A'), ('B', 'Requirement B')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Creative Designer', 'Creative Designer')], max_length=225),
        ),
    ]
