# Generated by Django 3.2.3 on 2021-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210615_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='prerequisites',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Creative Designer', 'Creative Designer'), ('Finance', 'Finance')], max_length=225),
        ),
    ]
