# Generated by Django 3.2.3 on 2021-06-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210615_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='prerequisites',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Creative Designer', 'Creative Designer'), ('Engineering', 'Engineering')], max_length=225),
        ),
    ]
