# Generated by Django 3.2.3 on 2021-06-15 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210615_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Creative Designer', 'Creative Designer'), ('Finance', 'Finance')], max_length=225),
        ),
    ]
