# Generated by Django 3.2.3 on 2021-06-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210615_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Creative Designer', 'Creative Designer'), ('Engineering', 'Engineering')], max_length=225),
        ),
    ]
