# Generated by Django 3.2.3 on 2021-06-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20210616_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('mission', models.TextField()),
                ('news_title', models.CharField(max_length=225)),
                ('news_image', models.ImageField(upload_to='images/')),
                ('news_desc', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Creative Designer', 'Creative Designer')], max_length=225),
        ),
    ]
