# Generated by Django 3.2.3 on 2021-06-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20210616_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=225)),
                ('news_image', models.ImageField(upload_to='images/')),
                ('news_desc', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='news_desc',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='news_image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='news_title',
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Creative Designer', 'Creative Designer'), ('Finance', 'Finance'), ('Engineering', 'Engineering')], max_length=225),
        ),
    ]
