# Generated by Django 3.2.3 on 2021-06-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20210617_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactu',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactu',
            name='email',
            field=models.EmailField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='contactu',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='contactu',
            name='phone_no',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
