# Generated by Django 3.2.3 on 2021-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20210617_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('website', models.CharField(blank=True, max_length=225, null=True)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WholeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=225)),
                ('fname', models.CharField(max_length=225)),
                ('lname', models.CharField(max_length=225)),
                ('ctitle', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('phnumber', models.CharField(max_length=225)),
                ('fnum', models.CharField(max_length=225)),
                ('product_choice', models.CharField(choices=[('Solid Neon Adaptor', 'Solid Neon Adaptor'), ('Solid Neon Blunt Box', 'Solid Neon Blunt Box'), ('Royal Splits Collection', 'Royal Splits Collection'), ('Special Order', 'Special Order')], max_length=225)),
                ('quantity', models.CharField(max_length=3)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('zip_code', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('federal_tax_id', models.CharField(max_length=225)),
                ('reseller_lisence', models.CharField(max_length=225)),
                ('inst_id', models.CharField(max_length=225)),
                ('fb_id', models.CharField(max_length=225)),
                ('shipping_add_field', models.CharField(choices=[('Residential Address', 'Residential Address'), ('Commercial Address', 'Commercial Address')], max_length=225)),
                ('shipping_add', models.TextField()),
                ('shipping_city', models.CharField(max_length=225)),
                ('shipping_state', models.CharField(max_length=225)),
                ('shipping_zip', models.CharField(max_length=225)),
                ('shipping_country', models.CharField(max_length=225)),
                ('shipping_person_name', models.CharField(max_length=225)),
                ('shipping_person_num', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Creative Designer', 'Creative Designer'), ('Engineering', 'Engineering')], max_length=225),
        ),
    ]
