# Generated by Django 3.2.3 on 2021-06-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20210617_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Finance', 'Finance'), ('Creative Designer', 'Creative Designer')], max_length=225),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='city',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='cname',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='country',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='ctitle',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='email',
            field=models.EmailField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='fb_id',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='federal_tax_id',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='fname',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='fnum',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='inst_id',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='lname',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='phnumber',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='product_choice',
            field=models.CharField(choices=[('Solid Neon Adaptor', 'Solid Neon Adaptor'), ('Solid Neon Blunt Box', 'Solid Neon Blunt Box'), ('Royal Splits Collection', 'Royal Splits Collection'), ('Special Order', 'Special Order')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='quantity',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='reseller_lisence',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='shipping_add',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='shipping_add_field',
            field=models.CharField(choices=[('Residential Address', 'Residential Address'), ('Commercial Address', 'Commercial Address')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='shipping_city',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='shipping_country',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='shipping_person_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='shipping_person_num',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='shipping_state',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='shipping_zip',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='state',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='zip_code',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
