# Generated by Django 3.2.3 on 2021-06-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20210618_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Creative Designer', 'Creative Designer'), ('Engineering', 'Engineering'), ('Finance', 'Finance')], max_length=225),
        ),
    ]
