# Generated by Django 3.2.3 on 2021-06-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20210618_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Creative Designer', 'Creative Designer'), ('Finance', 'Finance')], max_length=225),
        ),
    ]
