# Generated by Django 3.2.3 on 2021-06-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20210619_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.address'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Creative Designer', 'Creative Designer'), ('Engineering', 'Engineering'), ('Finance', 'Finance')], max_length=225),
        ),
    ]
