# Generated by Django 3.2.3 on 2021-06-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_auto_20210621_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Engineering', 'Engineering'), ('Creative Designer', 'Creative Designer')], max_length=225),
        ),
    ]
