# Generated by Django 3.2.3 on 2021-06-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20210623_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Job2', 'Job2'), ('Job3', 'Job3'), ('Creative Designer', 'Creative Designer'), ('Job1', 'Job1'), ('Finance', 'Finance')], max_length=225),
        ),
    ]
