# Generated by Django 3.2.3 on 2021-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20210627_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Job1', 'Job1'), ('Engineering', 'Engineering'), ('Job3', 'Job3'), ('Job2', 'Job2'), ('Finance', 'Finance'), ('Creative Designer', 'Creative Designer')], max_length=225),
        ),
    ]
