# Generated by Django 3.2.3 on 2021-06-27 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0060_auto_20210627_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Job2', 'Job2'), ('Creative Designer', 'Creative Designer'), ('Finance', 'Finance'), ('Job1', 'Job1'), ('Engineering', 'Engineering'), ('Job3', 'Job3')], max_length=225),
        ),
    ]
