# Generated by Django 3.2.3 on 2021-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20210627_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Job2', 'Job2'), ('Finance', 'Finance'), ('Job3', 'Job3'), ('Job1', 'Job1'), ('Engineering', 'Engineering'), ('Creative Designer', 'Creative Designer')], max_length=225),
        ),
    ]
