# Generated by Django 3.2.3 on 2021-07-04 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0068_auto_20210704_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Job3', 'Job3'), ('Engineering', 'Engineering'), ('Job2', 'Job2'), ('Creative Designer', 'Creative Designer'), ('Job1', 'Job1'), ('Finance', 'Finance')], max_length=225),
        ),
    ]
